# Generated by Django 2.1.4 on 2019-02-08 15:42

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjTinderUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=250, unique=True)),
                ('age', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(130)])),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], db_index=True, max_length=1)),
                ('preferred_sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('preferred_age_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(130)])),
                ('preferred_age_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(130)])),
                ('last_location', django.contrib.gis.db.models.fields.PointField(max_length=40, null=True, srid=4326)),
                ('preferred_radius', models.IntegerField(default=5, help_text='in kilometers')),
            ],
        ),
    ]
